- name: Update apt repo
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
    
- name: Install additions
  apt:
    name: "{{ packages }}"
    state: present
    
- name: Install pip additions
  pip:
    name: "{{ pip_packages }}"
    state: present