---

- hosts: all
  become: yes
  roles:
  - kernel_update
  - apt_update
  - docker_install
  - script
    tags: script
  - build
    tags: build
  

  tasks:

  - name: Success
    debug:
      msg: The playbook operation has been successfully completed. Please open your browser and enter the IP address of the computer for which the metrics were collected to view the information.
