- name: Install dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes

- name: Add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository to apt
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Docker
  apt:
    name: "{{ docker_packages }}"
    state: latest
    update_cache: yes

- name: Check Docker is active
  service:
    name: docker
    state: started
    enabled: yes

- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present
    
- name: adding user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
