- name: Create directory
  file:
    path: "{{ dest }}"
    state: directory
    
- name: Download packages
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ dest }}"
    mode: '0440'
  loop: "{{ links }}"
  
- name: Change the working directory and install packages
  ansible.builtin.command: dpkg -i {{ item }}
  args:
    chdir: "{{ dest }}"
  loop: "{{ packages }}"